version: '3'

services:
    core:
        build: .
        container_name: bitcoin
        hostname: bitcoin
        ports:
        - "5000:5000"
        volumes:
        - /mnt/ELEMENTS/bitcoin:/root/.bitcoin
        stdin_open: true # -i
        tty: true # -t
