version: '3'

services:
  core:
    build: .
    container_name: bitcoin
    hostname: bitcoin
    ports:
      - "5000:5000"
    volumes:
      - /tmp/bitcoin:/root/.bitcoin # Pick persistent location on host
